services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile.phoenix
    container_name: phoenix-observability
    ports:
      - "6006:6006"  # Phoenix UI
      - "4317:4317"  # gRPC OTLP endpoint
      - "4318:4318"  # HTTP OTLP endpoint
    environment:
      - PHOENIX_PROJECT_NAME=documents-browser-app
      - PHOENIX_DATA_DIR=/app/data
    volumes:
      - phoenix_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  typesense:
    image: typesense/typesense:27.1
    container_name: typesense-search
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-xyz}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

volumes:
  phoenix_data:
    driver: local
  typesense_data:
    driver: local

networks:
  app-network:
    driver: bridge